<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 0,
                'title' => 'Барановичи',
                'national_name' => 'Баранавічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 0,
                'title' => 'Брест',
                'national_name' => 'Брэст',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 0,
                'title' => 'Пинск',
                'national_name' => 'Пінск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 2,
                'title' => 'Берёза',
                'national_name' => 'Бяроза',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 2,
                'title' => 'Белоозёрск',
                'national_name' => 'Белаазёрск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 4,
                'title' => 'Ганцевичи',
                'national_name' => 'Ганцавічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 5,
                'title' => 'Дрогичин',
                'national_name' => 'Драгічын',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 6,
                'title' => 'Жабинка',
                'national_name' => 'Жабінка',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 7,
                'title' => 'Иваново',
                'national_name' => 'Іванава',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 8,
                'title' => 'Коссово',
                'national_name' => 'Косава',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 9,
                'title' => 'Каменец',
                'national_name' => 'Камянец',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 9,
                'title' => 'Высокое',
                'national_name' => 'Высокае',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 10,
                'title' => 'Кобрин',
                'national_name' => 'Кобрын',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 11,
                'title' => 'Лунинец',
                'national_name' => 'Лунінец',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 11,
                'title' => 'Микашевичи',
                'national_name' => 'Мікашэвічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 12,
                'title' => 'Ляховичи',
                'national_name' => 'Ляхавічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 13,
                'title' => 'Малорита',
                'national_name' => 'Маларыта',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 15,
                'title' => 'Пружаны',
                'national_name' => 'Пружаны',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 16,
                'title' => 'Столин',
                'national_name' => 'Столін',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'region_id' => 16,
                'title' => 'Давид-Городок',
                'national_name' => 'Давыд-Гарадок',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 0,
                'title' => 'Витебск',
                'national_name' => 'Віцебск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 0,
                'title' => 'Новополоцк',
                'national_name' => 'Наваполацк',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 17,
                'title' => 'Бешенковичи',
                'national_name' => 'Бешанковічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 18,
                'title' => 'Браслав',
                'national_name' => 'Браслаў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 19,
                'title' => 'Верхнедвинск',
                'national_name' => 'Верхнядзвінск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 21,
                'title' => 'Глубокое',
                'national_name' => 'Глыбокае',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 22,
                'title' => 'Городок',
                'national_name' => 'Гарадок',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 23,
                'title' => 'Докшицы',
                'national_name' => 'Докшыцы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 24,
                'title' => 'Дубровно',
                'national_name' => 'Дуброўна',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 25,
                'title' => 'Лепель',
                'national_name' => 'Лепель',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 26,
                'title' => 'Лиозно',
                'national_name' => 'Лёзна',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 27,
                'title' => 'Миоры',
                'national_name' => 'Міёры',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 27,
                'title' => 'Дисна',
                'national_name' => 'Дзісна',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 28,
                'title' => 'Орша',
                'national_name' => 'Орша',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 28,
                'title' => 'Барань',
                'national_name' => 'Барань',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 29,
                'title' => 'Полоцк',
                'national_name' => 'Полоцк',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 30,
                'title' => 'Поставы',
                'national_name' => 'Паставы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 31,
                'title' => 'Россоны',
                'national_name' => 'Расоны',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 32,
                'title' => 'Сенно',
                'national_name' => 'Сянно',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 33,
                'title' => 'Толочин',
                'national_name' => 'Талачын',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 34,
                'title' => 'Ушачи',
                'national_name' => 'Ушачы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 35,
                'title' => 'Чашники',
                'national_name' => 'Чашнікі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 35,
                'title' => 'Новолукомль',
                'national_name' => 'Новалукомль',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 36,
                'title' => 'Шарковщина',
                'national_name' => 'Шаркаўшчына',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'region_id' => 37,
                'title' => 'Шумилино',
                'national_name' => 'Шуміліна',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 0,
                'title' => 'Гомель',
                'national_name' => 'Гомель',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 38,
                'title' => 'Брагин',
                'national_name' => 'Брагін',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 39,
                'title' => 'Буда-Кошелёво',
                'national_name' => 'Буда-Кашалёва',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 40,
                'title' => 'Ветка',
                'national_name' => 'Ветка',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 42,
                'title' => 'Добруш',
                'national_name' => 'Добруш',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 43,
                'title' => 'Ельск',
                'national_name' => 'Ельск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 44,
                'title' => 'Житковичи',
                'national_name' => 'Жыткавічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 44,
                'title' => 'Туров',
                'national_name' => 'Тураў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 45,
                'title' => 'Жлобин',
                'national_name' => 'Жлобін',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 46,
                'title' => 'Калинковичи',
                'national_name' => 'Калінкавічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 47,
                'title' => 'Корма',
                'national_name' => 'Карма',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 48,
                'title' => 'Лельчицы',
                'national_name' => 'Лельчыцы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 49,
                'title' => 'Лоев',
                'national_name' => 'Лоеў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 50,
                'title' => 'Мозырь',
                'national_name' => 'Мазыр',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 51,
                'title' => 'Наровля',
                'national_name' => 'Нароўля',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 52,
                'title' => 'Октябрьский',
                'national_name' => 'Акцябрскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 53,
                'title' => 'Петриков',
                'national_name' => 'Петрыкаў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 54,
                'title' => 'Речица',
                'national_name' => 'Рэчыца',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 54,
                'title' => 'Василевичи',
                'national_name' => 'Васілевічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 55,
                'title' => 'Рогачёв',
                'national_name' => 'Рагачоў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 56,
                'title' => 'Светлогорск',
                'national_name' => 'Светлагорск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 57,
                'title' => 'Хойники',
                'national_name' => 'Хойнікі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'region_id' => 58,
                'title' => 'Чечерск',
                'national_name' => 'Чачэрск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 0,
                'title' => 'Гродно',
                'national_name' => 'Гродна (Гародня)',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 59,
                'title' => 'Большая Берестовица',
                'national_name' => 'Вялікая Бераставіца',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 60,
                'title' => 'Волковыск',
                'national_name' => 'Ваўкавыск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 61,
                'title' => 'Вороново',
                'national_name' => 'Воранава',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 62,
                'title' => 'Скидель',
                'national_name' => 'Скідзель',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 63,
                'title' => 'Дятлово',
                'national_name' => 'Дзятлава',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 64,
                'title' => 'Зельва',
                'national_name' => 'Зэльва',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 65,
                'title' => 'Ивье',
                'national_name' => 'Іўе',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 66,
                'title' => 'Кореличи',
                'national_name' => 'Карэлічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 67,
                'title' => 'Лида',
                'national_name' => 'Ліда',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 67,
                'title' => 'Берёзовка',
                'national_name' => 'Бярозаўка',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 68,
                'title' => 'Мосты',
                'national_name' => 'Масты',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 69,
                'title' => 'Новогрудок',
                'national_name' => 'Навагрудак (Наваградак)',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 70,
                'title' => 'Ошмяны',
                'national_name' => 'Ашмяны',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 71,
                'title' => 'Островец',
                'national_name' => 'Астравец',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 72,
                'title' => 'Свислочь',
                'national_name' => 'Свіслач',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 73,
                'title' => 'Слоним',
                'national_name' => 'Слонім',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 74,
                'title' => 'Сморгонь',
                'national_name' => 'Смаргонь (Смаргоні)',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'region_id' => 75,
                'title' => 'Щучин',
                'national_name' => 'Шчучын',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 0,
                'title' => 'Жодино',
                'national_name' => 'Жодзіна',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 0,
                'title' => 'Минск',
                'national_name' => 'Мінск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 76,
                'title' => 'Березино',
                'national_name' => 'Беразіно',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 77,
                'title' => 'Борисов',
                'national_name' => 'Барысаў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 78,
                'title' => 'Вилейка',
                'national_name' => 'Вілейка',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 79,
                'title' => 'Воложин',
                'national_name' => 'Валожын',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 80,
                'title' => 'Дзержинск',
                'national_name' => 'Дзяржынск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 80,
                'title' => 'Фаниполь',
                'national_name' => 'Фаніпаль',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 81,
                'title' => 'Клецк',
                'national_name' => 'Клецк',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 82,
                'title' => 'Копыль',
                'national_name' => 'Капыль',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 83,
                'title' => 'Крупки',
                'national_name' => 'Крупкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 84,
                'title' => 'Логойск',
                'national_name' => 'Лагойск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 85,
                'title' => 'Любань',
                'national_name' => 'Любань',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 86,
                'title' => 'Заславль',
                'national_name' => 'Заслаўе',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 87,
                'title' => 'Молодечно',
                'national_name' => 'Маладзечна',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 88,
                'title' => 'Мядель',
                'national_name' => 'Мядзел',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 89,
                'title' => 'Несвиж',
                'national_name' => 'Нясвіж',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 90,
                'title' => 'Марьина Горка',
                'national_name' => 'Мар’іна Горка',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 91,
                'title' => 'Слуцк',
                'national_name' => 'Слуцк, Слуцак',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 92,
                'title' => 'Смолевичи',
                'national_name' => 'Смалявічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 93,
                'title' => 'Солигорск',
                'national_name' => 'Салігорск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 94,
                'title' => 'Старые Дороги',
                'national_name' => 'Старыя Дарогі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 95,
                'title' => 'Столбцы',
                'national_name' => 'Стоўбцы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 96,
                'title' => 'Узда',
                'national_name' => 'Узда',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'region_id' => 97,
                'title' => 'Червень',
                'national_name' => 'Чэрвень',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 0,
                'title' => 'Бобруйск',
                'national_name' => 'Бабруйск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 0,
                'title' => 'Могилёв',
                'national_name' => 'Магілёў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 98,
                'title' => 'Белыничи',
                'national_name' => 'Бялынічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 100,
                'title' => 'Быхов',
                'national_name' => 'Быхаў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 101,
                'title' => 'Глуск',
                'national_name' => 'Глуск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 102,
                'title' => 'Горки',
                'national_name' => 'Горкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 103,
                'title' => 'Дрибин',
                'national_name' => 'Дрыбін',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 104,
                'title' => 'Кировск',
                'national_name' => 'Кіраўск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 105,
                'title' => 'Климовичи',
                'national_name' => 'Клімавічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 106,
                'title' => 'Кличев',
                'national_name' => 'Клічаў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 107,
                'title' => 'Костюковичи',
                'national_name' => 'Касцюковічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 108,
                'title' => 'Краснополье',
                'national_name' => 'Краснаполле',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 109,
                'title' => 'Кричев',
                'national_name' => 'Крычаў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 110,
                'title' => 'Круглое',
                'national_name' => 'Круглае',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 112,
                'title' => 'Мстиславль',
                'national_name' => 'Мсціслаў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 113,
                'title' => 'Осиповичи',
                'national_name' => 'Асіповічы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 114,
                'title' => 'Славгород',
                'national_name' => 'Слаўгарад',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 115,
                'title' => 'Хотимск',
                'national_name' => 'Хоцімск',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 116,
                'title' => 'Чаусы',
                'national_name' => 'Чавусы',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 117,
                'title' => 'Чериков',
                'national_name' => 'Чэрыкаў',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'region_id' => 118,
                'title' => 'Шклов',
                'national_name' => 'Шклоў',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 119,
                'title' => 'Бялобжеги',
                'national_name' => 'Białobrzegi',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 119,
                'title' => 'Выщмежице',
                'national_name' => 'Wyśmierzyce',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 120,
                'title' => 'Варшава',
                'national_name' => 'Warszawa',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 121,
                'title' => 'Ломянки',
                'national_name' => 'Łomianki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 121,
                'title' => 'Блонье',
                'national_name' => 'Błonie',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 121,
                'title' => 'Ожарув-Мазовецкий',
                'national_name' => 'Ożarów Mazowiecki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 122,
                'title' => 'Венгрув',
                'national_name' => 'Węgrów',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 122,
                'title' => 'Лохув',
                'national_name' => 'Łochów',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 123,
                'title' => 'Воломин',
                'national_name' => 'Wołomin',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 123,
                'title' => 'Зомбки',
                'national_name' => 'Ząbki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 123,
                'title' => 'Марки',
                'national_name' => 'Marki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 123,
                'title' => 'Кобылка',
                'national_name' => 'Kobyłka',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 123,
                'title' => 'Желёнка',
                'national_name' => 'Zielonka',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 123,
                'title' => 'Радзымин',
                'national_name' => 'Radzymin',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 123,
                'title' => 'Тлушч',
                'national_name' => 'Tłuszcz',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 124,
                'title' => 'Вышкув',
                'national_name' => 'Wyszków',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 125,
                'title' => 'Гарволин',
                'national_name' => 'Garwolin',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 125,
                'title' => 'Ласкажев',
                'national_name' => 'Łaskarzew',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 125,
                'title' => 'Пилава',
                'national_name' => 'Pilawa',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 125,
                'title' => 'Желехув',
                'national_name' => 'Żelechów',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 126,
                'title' => 'Гостынин',
                'national_name' => 'Gostynin',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 126,
                'title' => 'Санники',
                'national_name' => 'Sanniki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 127,
                'title' => 'Гродзиск-Мазовецки',
                'national_name' => 'Grodzisk Mazowiecki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 127,
                'title' => 'Милановек',
                'national_name' => 'Milanówek',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 127,
                'title' => 'Подкова Лещна',
                'national_name' => 'Podkowa Leśna',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 128,
                'title' => 'Груец',
                'national_name' => 'Grójec',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 128,
                'title' => 'Варка',
                'national_name' => 'Warka',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 128,
                'title' => 'Нове Място над Пилицо',
                'national_name' => 'Nowe Miasto nad Pilicą',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 128,
                'title' => 'Могельница',
                'national_name' => 'Mogielnica',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 129,
                'title' => 'Жирардув',
                'national_name' => 'Żyrardów',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 129,
                'title' => 'Мшчонув',
                'national_name' => 'Mszczonów',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 130,
                'title' => 'Журомин',
                'national_name' => 'Żuromin',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 130,
                'title' => 'Бежунь',
                'national_name' => 'Bieżuń',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 130,
                'title' => 'Любовидз',
                'national_name' => 'Lubowidz',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 131,
                'title' => 'Зволень',
                'national_name' => 'Zwoleń',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 132,
                'title' => 'Козенице',
                'national_name' => 'Kozienice',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 133,
                'title' => 'Легьоново',
                'national_name' => 'Legionowo',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 133,
                'title' => 'Сероцк',
                'national_name' => 'Serock',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 134,
                'title' => 'Липско',
                'national_name' => 'Lipsko',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 135,
                'title' => 'Лосице',
                'national_name' => 'Łosice',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 136,
                'title' => 'Макув-Мазовецки',
                'national_name' => 'Maków Mazowiecki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 136,
                'title' => 'Ружань',
                'national_name' => 'Różan',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 137,
                'title' => 'Миньск-Мазовецки',
                'national_name' => 'Mińsk Mazowiecki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 137,
                'title' => 'Сулейувек',
                'national_name' => 'Sulejówek',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 137,
                'title' => 'Халинув',
                'national_name' => 'Halinów',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 137,
                'title' => 'Мрозы',
                'national_name' => 'Mrozy',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 137,
                'title' => 'Калушин',
                'national_name' => 'Kałuszyn',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 138,
                'title' => 'Млава',
                'national_name' => 'Mława',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 139,
                'title' => 'Новы-Двур-Мазовецки',
                'national_name' => 'Nowy Dwór Mazowiecki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 139,
                'title' => 'Нащельск',
                'national_name' => 'Nasielsk',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 139,
                'title' => 'Закрочин',
                'national_name' => 'Zakroczym',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 140,
                'title' => 'Остроленка',
                'national_name' => 'Ostrołęka',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 140,
                'title' => 'Мышинец',
                'national_name' => 'Myszyniec',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 141,
                'title' => 'Острув-Мазовецка',
                'national_name' => 'Ostrów Mazowiecka',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 141,
                'title' => 'Брок',
                'national_name' => 'Brok',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 142,
                'title' => 'Отвоцк',
                'national_name' => 'Otwock',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 142,
                'title' => 'Юзефув',
                'national_name' => 'Józefów',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 142,
                'title' => 'Карчев',
                'national_name' => 'Karczew',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 143,
                'title' => 'Плоньск',
                'national_name' => 'Płońsk',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 143,
                'title' => 'Рачонж',
                'national_name' => 'Raciąż',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 144,
                'title' => 'Плоцк',
                'national_name' => 'Płock',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 144,
                'title' => 'Гомбин',
                'national_name' => 'Gąbin',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 144,
                'title' => 'Дробин',
                'national_name' => 'Drobin',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 144,
                'title' => 'Вышогруд',
                'national_name' => 'Wyszogród',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 145,
                'title' => 'Прушкув',
                'national_name' => 'Pruszków',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 145,
                'title' => 'Пястув',
                'national_name' => 'Piastów',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 145,
                'title' => 'Брвинув',
                'national_name' => 'Brwinów',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 146,
                'title' => 'Пултуск',
                'national_name' => 'Pułtusk',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 147,
                'title' => 'Пшасныш',
                'national_name' => 'Przasnysz',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 147,
                'title' => 'Хожеле',
                'national_name' => 'Chorzele',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 148,
                'title' => 'Пшисуха',
                'national_name' => 'Przysucha',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 149,
                'title' => 'Пясечно',
                'national_name' => 'Piaseczno',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 149,
                'title' => 'Констанцин-Езьорна',
                'national_name' => 'Konstancin-Jeziorna',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 149,
                'title' => 'Гура Калварья',
                'national_name' => 'Góra Kalwaria',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 149,
                'title' => 'Тарчин',
                'national_name' => 'Tarczyn',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 150,
                'title' => 'Радом',
                'national_name' => 'Radom',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 150,
                'title' => 'Пионки',
                'national_name' => 'Pionki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 150,
                'title' => 'Илжа',
                'national_name' => 'Iłża',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 150,
                'title' => 'Скарышев',
                'national_name' => 'Skaryszew',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 151,
                'title' => 'Седльце',
                'national_name' => 'Siedlce',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 151,
                'title' => 'Морды',
                'national_name' => 'Mordy',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 152,
                'title' => 'Серпц',
                'national_name' => 'Sierpc',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 153,
                'title' => 'Соколув-Подляски',
                'national_name' => 'Sokołów Podlaski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 153,
                'title' => 'Косув Ляцки',
                'national_name' => 'Kosów Lacki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 154,
                'title' => 'Сохачев',
                'national_name' => 'Sochaczew',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 155,
                'title' => 'Цеханов',
                'national_name' => 'Ciechanów',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 155,
                'title' => 'Глиноецк',
                'national_name' => 'Glinojeck',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'region_id' => 156,
                'title' => 'Шидловец',
                'national_name' => 'Szydłowiec',
                'created_at' => now(),
            ],
        ];
        
        DB::table('cities')->insert($data);
    }
}
