<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'title' => 'Австрия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'AT',
                'symbol_alfa3' => 'AUT',
                'number_iso' => '040',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Албания',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'AL',
                'symbol_alfa3' => 'ALB',
                'number_iso' => '008',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Андорра',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'AD',
                'symbol_alfa3' => 'AND',
                'number_iso' => '020',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Беларусь',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'BY',
                'symbol_alfa3' => 'BLR',
                'number_iso' => '112',
                'visible' => 1,
                'created_at' => now(),
            ],
            [
                'title' => 'Бельгия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'BE',
                'symbol_alfa3' => 'BEL',
                'number_iso' => '056',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Болгария',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'BG',
                'symbol_alfa3' => 'BGR',
                'number_iso' => '100',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Босния и Герцеговина',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'BA',
                'symbol_alfa3' => 'BIH',
                'number_iso' => '070',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Венгрия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'HU',
                'symbol_alfa3' => 'HUN',
                'number_iso' => '348',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Германия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'DE',
                'symbol_alfa3' => 'DEU',
                'number_iso' => '276',
                'visible' => 1,
                'created_at' => now(),
            ],
            [
                'title' => 'Греция',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'GR',
                'symbol_alfa3' => 'GRC',
                'number_iso' => '300',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Дания',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'DK',
                'symbol_alfa3' => 'DNK',
                'number_iso' => '208',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Ирландия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'IE',
                'symbol_alfa3' => 'IRL',
                'number_iso' => '372',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Исландия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'IS',
                'symbol_alfa3' => 'ISL',
                'number_iso' => '352',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Испания',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'ES',
                'symbol_alfa3' => 'ESP',
                'number_iso' => '724',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Италия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'IT',
                'symbol_alfa3' => 'ITA',
                'number_iso' => '380',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Латвия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'LV',
                'symbol_alfa3' => 'LVA',
                'number_iso' => '428',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Литва',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'LT',
                'symbol_alfa3' => 'LTU',
                'number_iso' => '440',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Лихтенштейн',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'LI',
                'symbol_alfa3' => 'LIE',
                'number_iso' => '438',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Люксембург',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'LU',
                'symbol_alfa3' => 'LUX',
                'number_iso' => '442',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Мальта',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'MT',
                'symbol_alfa3' => 'MLT',
                'number_iso' => '470',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Молдова',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'MD',
                'symbol_alfa3' => 'MDA',
                'number_iso' => '498',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Монако',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'MC',
                'symbol_alfa3' => 'MCO',
                'number_iso' => '492',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Нидерланды',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'NL',
                'symbol_alfa3' => 'NLD',
                'number_iso' => '528',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Норвегия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'NO',
                'symbol_alfa3' => 'NOR',
                'number_iso' => '578',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Ватикан',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'VA',
                'symbol_alfa3' => 'VAT',
                'number_iso' => '336',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Польша',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'PL',
                'symbol_alfa3' => 'POL',
                'number_iso' => '616',
                'visible' => 1,
                'created_at' => now(),
            ],
            [
                'title' => 'Португалия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'PT',
                'symbol_alfa3' => 'PRT',
                'number_iso' => '620',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Македония',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'MK',
                'symbol_alfa3' => 'MKD',
                'number_iso' => '807',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Россия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'RU',
                'symbol_alfa3' => 'RUS',
                'number_iso' => '643',
                'visible' => 1,
                'created_at' => now(),
            ],
            [
                'title' => 'Румыния',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'RO',
                'symbol_alfa3' => 'ROU',
                'number_iso' => '642',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Сан-Марино',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'SM',
                'symbol_alfa3' => 'SMR',
                'number_iso' => '674',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Сербия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'RS',
                'symbol_alfa3' => 'SRB',
                'number_iso' => '688',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Словакия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'SK',
                'symbol_alfa3' => 'SVK',
                'number_iso' => '703',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Словения',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'SI',
                'symbol_alfa3' => 'SVN',
                'number_iso' => '705',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Великобритания',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'GB',
                'symbol_alfa3' => 'GBR',
                'number_iso' => '826',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Украина',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'UA',
                'symbol_alfa3' => 'UKR',
                'number_iso' => '804',
                'visible' => 1,
                'created_at' => now(),
            ],
            [
                'title' => 'Фарерские острова',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'FO',
                'symbol_alfa3' => 'FRO',
                'number_iso' => '234',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Финляндия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'FI',
                'symbol_alfa3' => 'FIN',
                'number_iso' => '246',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Франция',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'FR',
                'symbol_alfa3' => 'FRA',
                'number_iso' => '250',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Хорватия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'HR',
                'symbol_alfa3' => 'HRV',
                'number_iso' => '191',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Черногория',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'ME',
                'symbol_alfa3' => 'MNE',
                'number_iso' => '499',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Чехия',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'CZ',
                'symbol_alfa3' => 'CZE',
                'number_iso' => '203',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Швейцария',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'CH',
                'symbol_alfa3' => 'CHE',
                'number_iso' => '756',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Швеция',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'SE',
                'symbol_alfa3' => 'SWE',
                'number_iso' => '752',
                'visible' => 0,
                'created_at' => now(),
            ],
            [
                'title' => 'Эстония',
                'national_name' => NULL,
                'symbol_alfa2 ' => 'EE',
                'symbol_alfa3' => 'EST',
                'number_iso' => '233',
                'visible' => 0,
                'created_at' => now(),
            ],
        ];
        
        DB::table('countries')->insert($data);
    }
}
