<?php

use Illuminate\Database\Seeder;

class HotelConditionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'hotel_id' => 1,
                'free_beds' => 0,
                'bed_price' => 25,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => 'хостел/ Нужно заранее уточнять кол. Мест. Любой срок. Комнаты не пересчитывают,если кто-то уехал',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 2,
                'free_beds' => 0,
                'bed_price' => 20,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => '550 zl/m/оплата на месяц за комнату/ при условии аренды на месяц  соимость по 20 zl/ с мая 18 zl',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 3,
                'free_beds' => 0,
                'bed_price' => 20,
                'collateral' => 980,
                'contract' => 1,
                'rental_conditions' => 'новая квартира на 6 чел. 600 Zl с ватт/фактура будет приходить на почту Семену Кириковичу',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 4,
                'free_beds' => 0,
                'bed_price' => 16.6,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'до 30.04.19/ уведомить за 2 недели',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 5,
                'free_beds' => 0,
                'bed_price' => 19.44,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'оплата переводом, условия хорошие - стоимость - 18+8% обычная комната/ для мастеров 20+8%/ оплата по недельно/ за неделю сообщать об отъезде работиков',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 6,
                'free_beds' => 22,
                'bed_price' => 20,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'По доезжающим - по факту. Игорь - по факту отъезда за прожитые дни',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 7,
                'free_beds' => 25,
                'bed_price' => 20,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'находится далеко от стройки/снимаем на 12 человек+ доплата по доезжающим',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 8,
                'free_beds' => 100,
                'bed_price' => 21,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => 'Хостел. Фактуры почтой предоплата с пересчетом след. Фактурой.',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 9,
                'free_beds' => 17,
                'bed_price' => 22,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => 'Хостел. Цены прописаны по месяцам в умове',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 10,
                'free_beds' => 20,
                'bed_price' => 21,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => 'Новый хостел. c 07/04/19 живут',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 11,
                'free_beds' => 18,
                'bed_price' => 20,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'Платили готувкой, дальше будет дешелев. Согласование количества мест и учет -Максим Позняк. Фактура будет приходить на почту Позняку и Крипиневич',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 12,
                'free_beds' => 18,
                'bed_price' => 20,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'Платили готувкой, дальше будет дешелев. Согласование количества мест и учет -Максим Позняк. Фактура будет приходить на почту Позняку и Крипиневич',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 13,
                'free_beds' => 0,
                'bed_price' => 22,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'готувка - оплата наличными - потом фактура/квартиры по городу',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 14,
                'free_beds' => 0,
                'bed_price' => 20,
                'collateral' => 2000,
                'contract' => 1,
                'rental_conditions' => 'Фактуру за месяц - оригинал забирает Семен Кирикович',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 15,
                'free_beds' => 0,
                'bed_price' => 32.4,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'если найм от мес.- 25zl, меньше -30zl.',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 16,
                'free_beds' => 0,
                'bed_price' => 20.83,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'условия хорошие, дом на 8 мест/ платим 5000 zł за месяц',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 17,
                'free_beds' => 0,
                'bed_price' => 25,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'можно платить по недельно, 25 zł',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 18,
                'free_beds' => 0,
                'bed_price' => 20,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'оплата вперед/если на мес - 600zl/мес за человека/ условия хорошие.',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 19,
                'free_beds' => 0,
                'bed_price' => 27.8,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 20,
                'free_beds' => 0,
                'bed_price' => 21.66,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => 'хостел/ 21,66 zl при оплате за мес',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 21,
                'free_beds' => 0,
                'bed_price' => 27,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'оплата наличными, нет интернета',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 22,
                'free_beds' => 0,
                'bed_price' => 21.66,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => 'оплата на месяц 650 zl brutto/ условия хорошие',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 23,
                'free_beds' => 20,
                'bed_price' => 20,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'оплата на месяц вперед. 600 zł - 4-х местный, 500 - 8 и 6 местные номера/ условия хорошие/ рускоговорящие',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 24,
                'free_beds' => 0,
                'bed_price' => 26.6,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'живем с 30.10 / условия хорошие',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 25,
                'free_beds' => 0,
                'bed_price' => 24.7,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 26,
                'free_beds' => 0,
                'bed_price' => 28,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'фактура будет выставляться по недельно',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 27,
                'free_beds' => 5,
                'bed_price' => 21.6,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => 'хостел/ оплата 2 раза в месяц/ для людей с авто/оплата наличными или по карточке на месте',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 28,
                'free_beds' => 0,
                'bed_price' => 20,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'оплатим первый раз наличными,дальше денежным переводом/ 600 zł d месяц/ brutto',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 29,
                'free_beds' => 0,
                'bed_price' => 21.21,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => 'Оплата на месяц. вместимость 8 человек - будет жить  6 работников и мастер. Оплата за 7,5 человек. фактура на емейл',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 30,
                'free_beds' => 0,
                'bed_price' => 28,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'на следующий месяц обещали снизить тоимость жилья',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 31,
                'free_beds' => 0,
                'bed_price' => 21.6,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => 'оплата по факту/Контакт и фактура.- Максим Позняк./+media',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 32,
                'free_beds' => 0,
                'bed_price' => 30,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'хостел/ есть 2, 5 местные номера',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 33,
                'free_beds' => 0,
                'bed_price' => 600,
                'collateral' => 2000,
                'contract' => 1,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 34,
                'free_beds' => 0,
                'bed_price' => 40,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'живем только одну неделю с 29.09 по 05.10',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 35,
                'free_beds' => 0,
                'bed_price' => 25,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'выставляют по недельно фактуры, можно делать корректировки',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 36,
                'free_beds' => 0,
                'bed_price' => 20,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 37,
                'free_beds' => 0,
                'bed_price' => 16.7,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'жилье от 15.10 до 15.11 - Зубко В. и его девушка',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 38,
                'free_beds' => 0,
                'bed_price' => 9,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'оплата наличными, без фактуры, 9 euro',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 39,
                'free_beds' => 0,
                'bed_price' => 20,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 40,
                'free_beds' => 0,
                'bed_price' => 17.5,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 41,
                'free_beds' => 0,
                'bed_price' => 16.76,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 42,
                'free_beds' => 0,
                'bed_price' => 26.27,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 43,
                'free_beds' => 0,
                'bed_price' => 0,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'вычтут за жил',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 44,
                'free_beds' => 0,
                'bed_price' => 9,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 45,
                'free_beds' => 0,
                'bed_price' => 19.5,
                'collateral' => 0,
                'contract' => 1,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 46,
                'free_beds' => 0,
                'bed_price' => 25,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'условия хорошие, платим вперед/ 25 zł',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 47,
                'free_beds' => 0,
                'bed_price' => 22.8,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'говорят на русском, новый хостел, оплата по недельно',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 48,
                'free_beds' => 0,
                'bed_price' => 25,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'платим за комнату/ 3 комнаты - 75 Zł, 4 комнаты - 100 zł',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 49,
                'free_beds' => 0,
                'bed_price' => 35,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '35 zł - мастер',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 50,
                'free_beds' => 0,
                'bed_price' => 27,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 51,
                'free_beds' => 0,
                'bed_price' => 22.8,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 52,
                'free_beds' => 0,
                'bed_price' => 25,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'живем с 03.10.2019, оплата по недельно/ срок оплаты будет 5-7 дней',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 53,
                'free_beds' => 0,
                'bed_price' => 21.1,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => 'резервировали пока на 1 неделю',
                'created_at' => now(),
            ],
            [
                'hotel_id' => 54,
                'free_beds' => 0,
                'bed_price' => 21.1,
                'collateral' => 0,
                'contract' => 0,
                'rental_conditions' => '',
                'created_at' => now(),
            ],
        ];
        
        DB::table('hotel_conditions')->insert($data);
    }
}
