<?php

use Illuminate\Database\Seeder;

class HotelsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'country_id' => 28,
                'city_id' => 222,
                'house_type' => 'хостел',
                'address' => 'ul. 11-Listopada',
                'contragent' => 'PROART/Iwona Czereszewska',
                'phone' => '888753624, 727 908 607, 727 908 611',
                'messenger' => 'iwczereszewska@wp.pl /  p-komorowski@wp.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 223,
                'house_type' => 'хостел',
                'address' => 'ul. Kilińskiego 172 pok 104,105, 109',
                'contragent' => 'APEX 2 Sp. Z o.o.',
                'phone' => '426 304 224',
                'messenger' => 'adm577@wp.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 223,
                'house_type' => 'квартира',
                'address' => 'ul.Piotrkowskiej 204/210, m. 2',
                'contragent' => 'Finanse i Ubezpieczeniea Tomasz Musiał',
                'phone' => '600 533 930 Tomasz',
                'messenger' => 't.musial1@wp.pl',
                'beds_number' => 6,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 223,
                'house_type' => 'хостел',
                'address' => 'ul. Wólczańska 135',
                'contragent' => 'Leonard Zdziechowski',
                'phone' => '696440095 Leonard',
                'messenger' => 'zdziechowski1@op.pl',
                'beds_number' => 25,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 223,
                'house_type' => 'хостел',
                'address' => 'ul. Lagiewnicka,16',
                'contragent' => '',
                'phone' => '793 310 090 Izie (ресепшен)/ 733 610 090 Patricija',
                'messenger' => 'jarek@empire.net.pl',
                'beds_number' => 41,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 230,
                'house_type' => 'хостел',
                'address' => 'ul. Bolesław',
                'contragent' => 'Stefania Czubajewska',
                'phone' => '696 076 087',
                'messenger' => 'noclegi.boleslaw@wp.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 230,
                'house_type' => 'хостел',
                'address' => 'ul. Kolonia',
                'contragent' => 'Stefania Czubajewska',
                'phone' => '696 076 087',
                'messenger' => 'stefania.czubajewska1@wp.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 232,
                'house_type' => 'хостел',
                'address' => 'ul. Wizwolenia, 9',
                'contragent' => 'Babex-2 Tour',
                'phone' => '697 979 582',
                'messenger' => 'babex2tour@wp.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 231,
                'house_type' => 'хостел',
                'address' => 'ul. Żeglarska 19',
                'contragent' => 'KDG Kamilla Specius',
                'phone' => '668 484 622',
                'messenger' => 'kamilaspecius1980@gmail.com/ dokumenty@erpxt.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 233,
                'house_type' => 'хостел',
                'address' => 'ul. Dluga,15,',
                'contragent' => 'Babex-2 Tour',
                'phone' => '',
                'messenger' => 'babex2tour@wp.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 229,
                'house_type' => 'хостел',
                'address' => 'ul. Trougguta 129',
                'contragent' => 'DANUTA',
                'phone' => '504 057 904 Казимир/ 500 655 448',
                'messenger' => 'as-noclegi@as-noclegi.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 229,
                'house_type' => 'хостел',
                'address' => 'ul. Sliczna 16',
                'contragent' => 'DANUTA',
                'phone' => '504 057 904 Казимир/ 500 655 448',
                'messenger' => 'as-noclegi@as-noclegi.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 229,
                'house_type' => 'квартира',
                'address' => 'ul. Sienkiewicza, 112',
                'contragent' => 'Lunatik',
                'phone' => '603 808 830 Ремек',
                'messenger' => '',
                'beds_number' => 10,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 235,
                'house_type' => 'хостел',
                'address' => 'ul. Kilińskiego 21',
                'contragent' => 'FHU \"REMIK\" Piotr Antoniak',
                'phone' => '659 409 838 Петр',
                'messenger' => '',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 163,
                'house_type' => 'хостел',
                'address' => 'ul. Jaktorowska 10/12',
                'contragent' => 'FHU DAREX',
                'phone' => '503 165 051',
                'messenger' => 'elabiuro@wp.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 236,
                'house_type' => 'хостел',
                'address' => 'ul. Zagrudż, 46',
                'contragent' => '',
                'phone' => '505 836 234 Wiesława/ 501 550713 Ewa',
                'messenger' => '',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 163,
                'house_type' => 'хостел',
                'address' => '1-go Maja',
                'contragent' => 'Beata',
                'phone' => '535 565 857',
                'messenger' => '',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'хостел',
                'address' => 'ul. Górczewska, 30',
                'contragent' => 'ALOHA Tomasz Szyszkowski',
                'phone' => '788788853',
                'messenger' => 'aloha.wola@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'квартира',
                'address' => 'GR. AK Polnoc 4, m 19',
                'contragent' => 'Jarema Dziewulski',
                'phone' => '536767676 Sonia/574954545',
                'messenger' => 'administracja@dziewulski.com.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'хостел',
                'address' => 'plac Kasztelański',
                'contragent' => 'EMPACC KLINGBAIL ŁUKASZ',
                'phone' => '537 777 270 Lukasz',
                'messenger' => 'empacc.bb@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'хостел',
                'address' => 'ul. Wyprawa, 20',
                'contragent' => '',
                'phone' => '502569411 Barbara',
                'messenger' => '',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'хостел',
                'address' => 'ul. Rzędzińska, 19',
                'contragent' => 'EMPACC KLINGBAIL ŁUKASZ',
                'phone' => '537 777 270',
                'messenger' => 'empacc.bb@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'хостел',
                'address' => 'ul. Młocarni, 33',
                'contragent' => 'Oleg Mysliwiec',
                'phone' => '577970711 - Дмитрий (заселение, оплата), 501 449 791 Олег (фактуры, хозяин)',
                'messenger' => 'oleg.mysliwiec@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'хостел',
                'address' => 'ul. Wolodyjowskiego 38a',
                'contragent' => 'TRuck Service Group',
                'phone' => '530 307 660 Artur/ 787209487 администратор',
                'messenger' => 'firmatecmail@postgres.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'хостел',
                'address' => 'ul. A.Pszenickiego, 3',
                'contragent' => 'Dzeta Spółka',
                'phone' => '530215706 Анастасия',
                'messenger' => 'kontakt@mojksiegowy24.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'хостел',
                'address' => 'ul. Racławicka, 112',
                'contragent' => 'VETA LOGISTIC',
                'phone' => '601950003 / 575046015 Игорь',
                'messenger' => 'veta.logistic@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'хостел',
                'address' => 'ul. Kulczynskiego, 2',
                'contragent' => 'pani Agnieżka',
                'phone' => '690 997 937 Agnieżka/ 576118586 - рецепшен/ 577947865 Andrzej',
                'messenger' => 'kontakt@hostelkulczynskiego.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 136,
                'house_type' => 'квартира',
                'address' => 'ul. Batalionu AK \"Parasol\" 14',
                'contragent' => '',
                'phone' => '660636070',
                'messenger' => '',
                'beds_number' => 6,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 224,
                'house_type' => 'квартира',
                'address' => 'ul. Rożdzieńskiego, 100/128',
                'contragent' => 'E-TCN',
                'phone' => '602 360 841',
                'messenger' => 'uzytkownicy@infakt.pl',
                'beds_number' => 8,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 224,
                'house_type' => 'хостел',
                'address' => 'ul. 1-go Maja, 41',
                'contragent' => ' Hostel Nina Janina Karcz',
                'phone' => '668138589',
                'messenger' => 'biuro@hostelnina.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 224,
                'house_type' => 'хостел',
                'address' => 'ul. Józefa Wolnego, 14',
                'contragent' => '',
                'phone' => '537306600',
                'messenger' => '',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 163,
                'house_type' => 'хостел',
                'address' => 'ul. Radziwiłłowska 58',
                'contragent' => 'Firma \"Domik\" Prezes - Tatjana Korzenko-Chudzynska',
                'phone' => '579 511 579',
                'messenger' => 'tanja7777tanja@gmail.com ',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 163,
                'house_type' => 'квартира',
                'address' => 'ul. Legionów Polskich, 24',
                'contragent' => '',
                'phone' => '884668665 Grzegorz',
                'messenger' => 'crane1905@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 228,
                'house_type' => 'хостел',
                'address' => 'ul. Gdańsk, 42',
                'contragent' => '',
                'phone' => '500431086',
                'messenger' => 'apartamentybg@wp.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 234,
                'house_type' => 'хостел',
                'address' => 'ul. Sienkiewicza, 3',
                'contragent' => 'Joanna Paw Busko Zdrój',
                'phone' => '602 295 383',
                'messenger' => 'ksawi18@onet.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 10,
                'city_id' => 237,
                'house_type' => 'хостел',
                'address' => 'Dreifaltigkeitsbergstr, 15 ',
                'contragent' => 'Ferienwohnung Familie Kostur',
                'phone' => '',
                'messenger' => 'arczi5polska@interia.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 10,
                'city_id' => 238,
                'house_type' => 'хостел',
                'address' => 'Künkelstr. 7 ',
                'contragent' => '',
                'phone' => '',
                'messenger' => '',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 10,
                'city_id' => 239,
                'house_type' => 'хостел',
                'address' => 'Steglitzer pl.5',
                'contragent' => 'Sosnovski',
                'phone' => '',
                'messenger' => '',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 10,
                'city_id' => 240,
                'house_type' => 'хостел',
                'address' => 'ul. Dammweg 7b',
                'contragent' => 'ZwieRaben Pension',
                'phone' => '61318936304',
                'messenger' => 'info@zweiraben-pension.de',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 10,
                'city_id' => 240,
                'house_type' => 'хостел',
                'address' => 'ul. Regerstr. 6',
                'contragent' => 'Vermietungen Rosanna Arnolds',
                'phone' => '4961312490859 / 4915757527476',
                'messenger' => 'rosanna.arnolds65@yahoo.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 10,
                'city_id' => 241,
                'house_type' => 'хостел',
                'address' => 'Verdistr.  114',
                'contragent' => 'Gestehaus Welker/ Samantha Welker',
                'phone' => '491778228795',
                'messenger' => 'samantha.welker@yahoo.de',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 10,
                'city_id' => 241,
                'house_type' => 'хостел',
                'address' => 'Boschetsrider st. 12',
                'contragent' => 'Euro-Asia Management',
                'phone' => '1702316912',
                'messenger' => 'j.farokhpey@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 10,
                'city_id' => 242,
                'house_type' => 'хостел',
                'address' => 'Solingenstr. 26',
                'contragent' => '',
                'phone' => '',
                'messenger' => '',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 10,
                'city_id' => 243,
                'house_type' => 'хостел',
                'address' => 'ul. Ohlen Hoff 4',
                'contragent' => 'Friederike Diestel',
                'phone' => '51431462',
                'messenger' => 'www.hof-diestel.de',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 227,
                'house_type' => 'хостел',
                'address' => 'ul. Nowosolska, 7',
                'contragent' => 'Maciej Siebert',
                'phone' => '516 213 516',
                'messenger' => 'kontakt@kwaternet.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 227,
                'house_type' => 'хостел',
                'address' => 'ul Gostyńska, 126',
                'contragent' => 'Empirre Magdalena Dolata',
                'phone' => '505 373 736',
                'messenger' => 'biuro@empirre.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 226,
                'house_type' => 'хостел',
                'address' => 'Hieronima Wietora 2',
                'contragent' => 'AMETYST',
                'phone' => '799 071453 Елена',
                'messenger' => 'ametystliving@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 226,
                'house_type' => 'хостел',
                'address' => 'ul.Hodura, 12',
                'contragent' => 'noclieg spoko',
                'phone' => '8824444221/ 793281048',
                'messenger' => 'nocleg.spoko@onet.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 226,
                'house_type' => 'хостел',
                'address' => 'Tatarska 5,',
                'contragent' => 'Hostel Aleja28',
                'phone' => '666854301',
                'messenger' => 'hostel@aleje28.pl ',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 226,
                'house_type' => 'хостел',
                'address' => 'ul. Karmelicka 50 /3',
                'contragent' => 'Das Hostel',
                'phone' => '798724825 - ресепшен/ 504527946 - хозяин pan Sebastian Ciaston',
                'messenger' => 'dashostel@outlook.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 226,
                'house_type' => 'хостел',
                'address' => 'ul. Karmelicka 10',
                'contragent' => 'AMETYST',
                'phone' => '799 071453 Елена',
                'messenger' => 'ametystliving@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 226,
                'house_type' => 'хостел',
                'address' => 'os. Złotej Jesieni, 7',
                'contragent' => 'NH Hostel',
                'phone' => '12 311 06 67',
                'messenger' => 'nh@nhhostel.pl',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 225,
                'house_type' => 'хостел',
                'address' => 'ul. Wójta Henryka, 44',
                'contragent' => 'Firma ACER',
                'phone' => '507049801  508186483',
                'messenger' => ' acer.zpiktz@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
            [
                'country_id' => 28,
                'city_id' => 225,
                'house_type' => 'хостел',
                'address' => 'ul. Staszica 30/2',
                'contragent' => 'Zaneta Lech-Pietraszko',
                'phone' => '575222813 Żaneta',
                'messenger' => ' noclegi.lubin@gmail.com',
                'beds_number' => 0,
                'created_at' => now(),
            ],
        ];
        
        DB::table('hotels')->insert($data);
    }
}
