<?php

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'parent_id' => 0,
                'sort' => 1,
                'name' => 'SK-BUD',
                'path' => '/',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 2,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 1,
                'sort' => 1,
                'name' => 'Кадры',
                'path' => 'human-resources',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 1,
                'sort' => 2,
                'name' => 'Финансы',
                'path' => 'accounting',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 2,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 1,
                'sort' => 3,
                'name' => 'Справочники',
                'path' => 'references',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 1,
                'sort' => 4,
                'name' => 'Настройки',
                'path' => 'settings',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 1,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 2,
                'sort' => 1,
                'name' => 'Кадровый ресурс',
                'path' => 'hr/personal-cards',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 2,
                'sort' => 2,
                'name' => 'Должностные назначения',
                'path' => 'hr/manning-orders',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 2,
                'sort' => 3,
                'name' => 'Бригады',
                'path' => 'hr/teams',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 2,
                'sort' => 4,
                'name' => 'Должностные перемещения работника',
                'path' => 'hr/allocations',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 2,
                'sort' => 5,
                'name' => 'Кадровая аналитика',
                'path' => 'hr/hr-analytics',
                'access_0' => 1,
                'access_1' => 1,
                'access_2' => 1,
                'access_3' => 0,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 1,
                'name' => 'Виды сдельных работ',
                'path' => 'acc/pieceworks',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 2,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 2,
                'name' => 'Табель отработанного времени',
                'path' => 'acc/base-timesheets',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 2,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 3,
                'name' => 'Начисления',
                'path' => 'acc/accruals',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 2,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 4,
                'name' => 'Удержания',
                'path' => 'acc/retentions',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 2,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 5,
                'name' => 'Расчет заработной платы',
                'path' => 'calc/payrolls',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 1,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 6,
                'name' => 'Расчетный лист по заработной плате',
                'path' => 'calc/paychecks',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 1,
                'access_4' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 7,
                'name' => 'Финансовая аналитика',
                'path' => 'calc/fin-analytics',
                'access_0' => 1,
                'access_1' => 1,
                'access_2' => 1,
                'access_3' => 0,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 1,
                'name' => 'Месяца',
                'path' => 'ref/months',
                'access_0' => 2,
                'access_1' => 1,
                'access_2' => 1,
                'access_3' => 0,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 2,
                'name' => 'Года',
                'path' => 'ref/years',
                'access_0' => 2,
                'access_1' => 1,
                'access_2' => 1,
                'access_3' => 0,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 3,
                'name' => 'Объекты',
                'path' => 'ref/objects',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 1,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 4,
                'name' => 'Подразделения компании',
                'path' => 'ref/departments',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 1,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 5,
                'name' => 'Государственный классификатор профессий',
                'path' => 'ref/position-professions',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 1,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 6,
                'name' => 'Должности',
                'path' => 'ref/positions',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 1,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 7,
                'name' => 'Классификатор начислений',
                'path' => 'ref/accrual-types',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 1,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 8,
                'name' => 'Классификатор удержаний',
                'path' => 'ref/retention-types',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 1,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 5,
                'sort' => 1,
                'name' => 'Пользователи системы',
                'path' => 'set/users',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 1,
                'access_4' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 5,
                'sort' => 1,
                'name' => 'Меню системы',
                'path' => 'set/menus',
                'access_0' => 2,
                'access_1' => 1,
                'access_2' => 0,
                'access_3' => 0,
                'access_4' => 0,
                'created_at' => now(),
            ],
        ];
        
        DB::table('menus')->insert($data);
    }
}
