<?php

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'parent_id' => 0,
                'sort' => 1,
                'name' => 'SK-BUD',
                'path' => '/',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 1,
                'sort' => 1,
                'name' => 'Кадры',
                'path' => 'human-resources',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 1,
                'sort' => 2,
                'name' => 'Финансы',
                'path' => 'accounting',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 1,
                'sort' => 3,
                'name' => 'Справочники',
                'path' => 'references',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 1,
                'sort' => 4,
                'name' => 'Настройки',
                'path' => 'settings',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 2,
                'sort' => 1,
                'name' => 'Карточка работника',
                'path' => 'hr/personal-cards',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 1,
                'name' => 'Адреса работника',
                'path' => 'hr/personal-addresses',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 2,
                'name' => 'Способы коммуникации с работником',
                'path' => 'hr/personal-communications',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 3,
                'name' => 'Паспорта работника',
                'path' => 'hr/personal-pasports',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 4,
                'name' => 'Гражданства работника',
                'path' => 'hr/personal-citizenships',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 5,
                'name' => 'Образование и квалификация работника',
                'path' => 'hr/personal-educations',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 6,
                'name' => 'Налоговая информация работника',
                'path' => 'hr/personal-taxes',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 7,
                'name' => 'Трудовой стараж работника',
                'path' => 'hr/work-experiences',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 8,
                'name' => 'Предыдущие места работы',
                'path' => 'hr/last-jobs',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 9,
                'name' => 'Страховые свидетельства работника',
                'path' => 'hr/insurance-certificates',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 10,
                'name' => 'Зарплатные карты работника',
                'path' => 'hr/salary-cards',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 11,
                'name' => 'Воинский учет работникa',
                'path' => 'hr/military-accountings',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 6,
                'sort' => 12,
                'name' => 'Близкое окружение работника',
                'path' => 'hr/employee-families',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 2,
                'sort' => 2,
                'name' => 'Кадровые документы',
                'path' => 'hr/documents',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 19,
                'sort' => 1,
                'name' => 'Найм и увольнение работника',
                'path' => 'hr/recruitment-orders',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 19,
                'sort' => 2,
                'name' => 'Должностные назначения',
                'path' => 'hr/manning-orders',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 19,
                'sort' => 3,
                'name' => 'Должностные перемещения работника',
                'path' => 'hr/allocations',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 19,
                'sort' => 4,
                'name' => 'Материальное обеспечение работника',
                'path' => 'hr/provisions',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 2,
                'sort' => 3,
                'name' => 'Пересечения границы работником',
                'path' => 'hr/border-crossings',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 22,
                'sort' => 1,
                'name' => 'Визы работника на пребывание в стране',
                'path' => 'hr/visa-statuses',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 22,
                'sort' => 2,
                'name' => 'Документы работника для получения визы',
                'path' => 'hr/visa-documents',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 22,
                'sort' => 3,
                'name' => 'Миграционный статус работника',
                'path' => 'hr/migration-statuses',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 22,
                'sort' => 4,
                'name' => 'Документы работника для легализации пребывания',
                'path' => 'hr/migration-documents',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 1,
                'name' => 'Наряды',
                'path' => 'acc/work-orders',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 29,
                'sort' => 1,
                'name' => 'Суммы нарядов',
                'path' => 'acc/work-orders-amounts',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 29,
                'sort' => 2,
                'name' => 'Распределение часов',
                'path' => 'acc/hours-balances',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 2,
                'name' => 'Табель отработанного времени',
                'path' => 'acc/base-timesheets',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 3,
                'name' => 'Отсутствия на работе',
                'path' => 'acc/absence-from-works',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 33,
                'sort' => 1,
                'name' => 'Отпуска',
                'path' => 'acc/vacations',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 33,
                'sort' => 2,
                'name' => 'Суммы отпускных',
                'path' => 'acc/vacation-amounts',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 4,
                'name' => 'Расчет начислений',
                'path' => 'acc/accrual-timesheets',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 36,
                'sort' => 1,
                'name' => 'Суммы начисления по подразделению',
                'path' => 'acc/department-accruals',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 36,
                'sort' => 2,
                'name' => 'Расчет сумм начислений работникам',
                'path' => 'acc/employee-accrual-calculations',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 36,
                'sort' => 3,
                'name' => 'Суммы начислений работникам',
                'path' => 'acc/employee-accruals',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 36,
                'sort' => 4,
                'name' => 'Суммы начислений работникам за месяц',
                'path' => 'acc/employee-accrual-months',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 36,
                'sort' => 5,
                'name' => 'Суммы начислений работникам за год',
                'path' => 'acc/employee-accrual-years',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 36,
                'sort' => 6,
                'name' => 'Переформирование начислений работникам',
                'path' => 'acc/employee-accrual-changes',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 36,
                'sort' => 7,
                'name' => 'Специальное питание',
                'path' => 'acc/special-eatings',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 1,
                'created_at' => now(),
            ],
            [
                'parent_id' => 36,
                'sort' => 8,
                'name' => 'Ошибки в расчете начислений работникам',
                'path' => 'acc/log-accrual-errors',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 3,
                'sort' => 5,
                'name' => 'Финансовые итоги',
                'path' => 'calc/accounting',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 45,
                'sort' => 1,
                'name' => 'Закрытие финансового периода',
                'path' => 'calc/closing-financial-periods',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 45,
                'sort' => 2,
                'name' => 'Подготовка расчета заработной платы',
                'path' => 'calc/payroll-preparations',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 45,
                'sort' => 3,
                'name' => 'Расчет заработной платы',
                'path' => 'calc/payrolls',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 45,
                'sort' => 4,
                'name' => 'Расчетный лист по заработной плате',
                'path' => 'calc/paychecks',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 1,
                'name' => 'Кадровые',
                'path' => 'ref/human-resources',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 1,
                'name' => 'Штатное расписание',
                'path' => 'ref/manning-tables',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 2,
                'name' => 'Должности',
                'path' => 'ref/positions',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 3,
                'name' => 'Категории должностей',
                'path' => 'ref/position-categories',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 4,
                'name' => 'Государственный классификатор профессий',
                'path' => 'ref/position-professions',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 5,
                'name' => 'Уровни квалификации (разряды, ранги)',
                'path' => 'ref/ranks',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 6,
                'name' => 'Уровни должностей',
                'path' => 'ref/subordinations',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 7,
                'name' => 'Виды трудовых отношений',
                'path' => 'ref/employment-types',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 8,
                'name' => 'Виды кадровых документов',
                'path' => 'ref/document-types',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 9,
                'name' => 'Основания увольнения работника',
                'path' => 'ref/dismissal-reasons',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 10,
                'name' => 'Уровни образования',
                'path' => 'ref/education-types',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 11,
                'name' => 'Режимы (формы) обучения',
                'path' => 'ref/study-modes',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 12,
                'name' => 'Способы коммуникации с работником',
                'path' => 'ref/communication-types',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 13,
                'name' => 'Семейное положение',
                'path' => 'ref/marital-statuses',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 50,
                'sort' => 14,
                'name' => 'Степень родства',
                'path' => 'ref/family-relation-types',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 2,
                'name' => 'Финансовые',
                'path' => 'ref/accounting',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 1,
                'name' => 'Алгоритмы начислений',
                'path' => 'ref/algorithms',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 2,
                'name' => 'Группы видов начислений',
                'path' => 'ref/accrual-groups',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 3,
                'name' => 'Классификатор начислений',
                'path' => 'ref/accruals',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 4,
                'name' => 'Зависимости начислений',
                'path' => 'ref/accrual-relations',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 5,
                'name' => 'Виды расчетов',
                'path' => 'ref/calculation-groups',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 6,
                'name' => 'Виды сдельных работ',
                'path' => 'ref/pieceworks',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 7,
                'name' => 'Единицы изменерия сдельных работ',
                'path' => 'ref/piecework-units',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 8,
                'name' => 'Бухгалтерские счета',
                'path' => 'ref/accounts',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 9,
                'name' => 'Классификатор налоговых ставок',
                'path' => 'ref/tax-rates',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 10,
                'name' => 'Классификатор сумм оплаты налогов',
                'path' => 'ref/tax-rate-amounts',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 11,
                'name' => 'Шкала расчета подоходного налога',
                'path' => 'ref/tax-scales',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 12,
                'name' => 'Валюты',
                'path' => 'ref/currencies',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 65,
                'sort' => 13,
                'name' => 'Текущие курсы валют',
                'path' => 'ref/currency-kurses',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 3,
                'name' => 'Общие',
                'path' => 'ref/general',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 1,
                'name' => 'Группы подразделений компании',
                'path' => 'ref/department-groups',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 2,
                'name' => 'Подразделения компании',
                'path' => 'ref/departments',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 3,
                'name' => 'Бригады',
                'path' => 'ref/teams',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 4,
                'name' => 'Группы объектов',
                'path' => 'ref/object-groups',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 5,
                'name' => 'Объекты',
                'path' => 'ref/objects',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 6,
                'name' => 'Группы формулировок для заполнения документов и форм ',
                'path' => 'ref/phrase-list-groups',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 7,
                'name' => 'Формулировки для заполнения документов и форм ',
                'path' => 'ref/phrase-lists',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 8,
                'name' => 'Классификатор графиков распределения рабочих часов',
                'path' => 'ref/hours-balance-classifiers',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 9,
                'name' => 'Виды отсутствия на работе',
                'path' => 'ref/grouping-types-of-absences',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 10,
                'name' => 'Классификатор отсутствия на работе',
                'path' => 'ref/absence-classifiers',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 11,
                'name' => 'Налоговые инспекции',
                'path' => 'ref/tax-offices',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 12,
                'name' => 'Получатели подоходного налога',
                'path' => 'ref/tax-recipients',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 13,
                'name' => 'Виды рабочих недель',
                'path' => 'ref/work-week-types',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 79,
                'sort' => 14,
                'name' => 'Группы инвалидности',
                'path' => 'ref/disabilities',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 4,
                'sort' => 4,
                'name' => 'Базовые',
                'path' => 'ref/base',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 94,
                'sort' => 1,
                'name' => 'Месяца',
                'path' => 'ref/months',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 94,
                'sort' => 2,
                'name' => 'Года',
                'path' => 'ref/years',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 94,
                'sort' => 3,
                'name' => 'Праздничные дни',
                'path' => 'ref/holidays',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 94,
                'sort' => 4,
                'name' => 'Национальности',
                'path' => 'ref/nationalities',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 94,
                'sort' => 5,
                'name' => 'Страны',
                'path' => 'ref/countries',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 94,
                'sort' => 6,
                'name' => 'Области (штаты, земели, воевудства)',
                'path' => 'ref/districts',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 94,
                'sort' => 7,
                'name' => 'Районы',
                'path' => 'ref/regions',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 94,
                'sort' => 8,
                'name' => 'Населенные пункты',
                'path' => 'ref/cities',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 94,
                'sort' => 9,
                'name' => 'Размеры одежды',
                'path' => 'ref/clothing-sizes',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 94,
                'sort' => 10,
                'name' => 'Размеры обуви',
                'path' => 'ref/shoe-sizes',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 2,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 5,
                'sort' => 1,
                'name' => 'Настройки финансовых параметров расчетов',
                'path' => 'set/calculation-setups',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 5,
                'sort' => 2,
                'name' => 'Реквизиты компании',
                'path' => 'set/company-datas',
                'access_0' => 2,
                'access_1' => 2,
                'access_2' => 1,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 5,
                'sort' => 3,
                'name' => 'Константы системы',
                'path' => 'set/constants',
                'access_0' => 2,
                'access_1' => 1,
                'access_2' => 0,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 107,
                'sort' => 1,
                'name' => 'Меню системы',
                'path' => 'set/menus',
                'access_0' => 2,
                'access_1' => 1,
                'access_2' => 0,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 5,
                'sort' => 4,
                'name' => 'Настройки восстановления базы данных',
                'path' => 'set/restore-databases',
                'access_0' => 2,
                'access_1' => 1,
                'access_2' => 0,
                'access_3' => 0,
                'created_at' => now(),
            ],
            [
                'parent_id' => 5,
                'sort' => 5,
                'name' => 'Настройки сохранения базы данных',
                'path' => 'set/save-databases',
                'access_0' => 2,
                'access_1' => 1,
                'access_2' => 0,
                'access_3' => 0,
                'created_at' => now(),
            ],
        ];
        
        DB::table('menus')->insert($data);
    }
}
