<?php

use Illuminate\Database\Seeder;

class ObjectsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'object_group_id' => 1,
                'code' => '07',
                'title' => 'B-07 Słupsk',
                'abbr' => 'B-07',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '19',
                'title' => 'B-19 BUDIMEX Łowicz',
                'abbr' => 'B-19',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '20',
                'title' => 'B-20 BUDIMEX Gdańsk',
                'abbr' => 'B-20',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '22',
                'title' => 'B-22 BUDIMEX Wrocław',
                'abbr' => 'B-22',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '23',
                'title' => 'B-23 BUDIMEX Kraków',
                'abbr' => 'B-23',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '24',
                'title' => 'B-24 BUDIMEX-2 Gdańsk',
                'abbr' => 'B-24',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '31',
                'title' => 'B-31 BUDIMEX Uniejów',
                'abbr' => 'B-31',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '32',
                'title' => 'B-32 BUDIMEX Warszawa',
                'abbr' => 'B-32',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '33',
                'title' => 'B-33 BUDIMEX Łódź Monopolis',
                'abbr' => 'B-33',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '34',
                'title' => 'B-34 BUDIMEX Łódź Off-Piotrkowska',
                'abbr' => 'B-34',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '36',
                'title' => 'B-36 MIRBUD Skierniewice',
                'abbr' => 'B-36',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '38',
                'title' => 'B-38 PRZEMBUD Sopot',
                'abbr' => 'B-38',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '39',
                'title' => 'B-39 MERX Zabrow',
                'abbr' => 'B-39',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '40',
                'title' => 'B-40 MIRBUD Brzeziny',
                'abbr' => 'B-40',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '41',
                'title' => 'B-41 POLBET Wrocław',
                'abbr' => 'B-41',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '42',
                'title' => 'B-42 SEMIK Błonie',
                'abbr' => 'B-42',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '43',
                'title' => 'B-43 MIRBUD Konin',
                'abbr' => 'B-43',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '44',
                'title' => 'В-44 TLC Rogowo',
                'abbr' => 'B-44',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '45',
                'title' => 'B-45 RBS Swidnica',
                'abbr' => 'B-45',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '46',
                'title' => 'B-46 WARBUD Łódź',
                'abbr' => 'B-46',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '47',
                'title' => 'B-47 JP Warszawa',
                'abbr' => 'B-47',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '48',
                'title' => 'B-48 POLBET Katowice',
                'abbr' => 'B-48',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '49',
                'title' => 'B-49 ERBUD Gdańsk',
                'abbr' => 'B-49',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '50',
                'title' => 'B-50 KONS Białystok',
                'abbr' => 'B-50',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '51',
                'title' => 'B-51 SBG Halle Germany',
                'abbr' => 'B-51',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '53',
                'title' => 'B-53 MIRBUD Łódź',
                'abbr' => 'B-53',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '54',
                'title' => 'B-54 POLBET Wrocław',
                'abbr' => 'B-54',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '55',
                'title' => 'B-55 POLBET Wrocław Afgańska',
                'abbr' => 'B-55',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '56',
                'title' => 'B-56 Gdańsk ErBud FOTOPLASTYKON',
                'abbr' => 'B-56',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '57',
                'title' => 'B-57 level Riverview Gdańsk',
                'abbr' => 'B-57',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '58',
                'title' => 'B-58 level Oliwski Park Gdańsk',
                'abbr' => 'B-58',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '59',
                'title' => 'B-59 CFE Wrocław',
                'abbr' => 'B-59',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '60',
                'title' => 'B-60 SBG Halle',
                'abbr' => 'B-60',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '61',
                'title' => 'B-61Grano Residence Gdańsk',
                'abbr' => 'B-61',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '62',
                'title' => 'B-62 Osiedle Foresta Gdańsk',
                'abbr' => 'B-62',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '63',
                'title' => 'B-63 SBG Leipzig',
                'abbr' => 'B-63',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '64',
                'title' => 'B-64 BUD-POS Wręcza',
                'abbr' => 'B-64',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '65',
                'title' => 'B-65 Budimex Warszawa Mokotów',
                'abbr' => 'B-65',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '66',
                'title' => 'B-66 Budimex Nowa Hala Wanien',
                'abbr' => 'B-66',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '67',
                'title' => 'B-67 Kowalski BAU Sylt Maybachstr. 8a',
                'abbr' => 'B-67',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '68',
                'title' => 'B-68 Budimex Alchemium Łódź',
                'abbr' => 'B-68',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '69',
                'title' => 'B-69 Kowalski BAU Sylt Norderstr. 73',
                'abbr' => 'B-69',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '70',
                'title' => 'B-70 Kowalski BAU Sylt Westerlandstr. 13',
                'abbr' => 'B-70',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '71',
                'title' => 'B-71 Kowalski BAU Syl Süderhörn 14-16',
                'abbr' => 'B-71',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '72',
                'title' => 'В-72 Budimex Bydgoszcz',
                'abbr' => 'B-72',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '73',
                'title' => 'B-73 Kowalski BAU GmbH Ostmark str. 13',
                'abbr' => 'B-73',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '74',
                'title' => 'B-74 POLBET Wrocław',
                'abbr' => 'B-74',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '75',
                'title' => 'B-75 ALSTAL Poddębic',
                'abbr' => 'B-75',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '76',
                'title' => 'B-76 Kowalski BAU GmbH FeldmarkStr. 22',
                'abbr' => 'B-76',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '77',
                'title' => 'B-77 CFE POLSKA Warszawa Białobrzeska',
                'abbr' => 'B-77',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '78',
                'title' => 'В-78 Korporacja Budowlana DORACO Gdynia',
                'abbr' => 'B-78',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '79',
                'title' => 'B-79 IDS-BUD S.A. Katowice',
                'abbr' => 'B-79',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '80',
                'title' => 'B-80 Budwoj Busko-Zrdój',
                'abbr' => 'B-80',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '81',
                'title' => 'B-81 BBS-Bau GmbH Germany',
                'abbr' => 'B-81',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '82',
                'title' => 'B-82 MOTA-ENGIL Warszawa Grodkowska',
                'abbr' => 'B-82',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '83',
                'title' => 'B-83 CFE POLSKA Warszawa Obozowa, 20',
                'abbr' => 'B-83',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '84',
                'title' => 'B-84 Mostostal Warszawa ul. Oś Krulewska',
                'abbr' => 'B-84',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '85',
                'title' => 'B-85 IDS-BUD Warszawa ul Konstruktorska, 8',
                'abbr' => 'B-85',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '86',
                'title' => 'B-86 Polbet Warszawa, ul. Iwanowa-Szajnowicza',
                'abbr' => 'B-86',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '87',
                'title' => 'B-87 Budimex 2K1F Kraków,',
                'abbr' => 'B-87',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '88',
                'title' => 'B-88 CFE, Poznań, ul. Smardzewska',
                'abbr' => 'B-88',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '89',
                'title' => 'B-89 BBS-Bau Germany Munich',
                'abbr' => 'B-89',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '90',
                'title' => 'B-90 BBS-Bau Mainz Rheinallee II',
                'abbr' => 'B-90',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '91',
                'title' => 'B-91 Prestige Warszawa ul. Stryjeńskich 15',
                'abbr' => 'B-91',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '92',
                'title' => 'B-92 Sosnowski Bau GmbH Dusseldorf',
                'abbr' => 'B-92',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '93',
                'title' => 'B-93 Strabag Wiskitki ul. Błońska',
                'abbr' => 'B-93',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '94',
                'title' => 'B-94 TLC Inwest Lubin, ul.Bema 8',
                'abbr' => 'B-94',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '95',
                'title' => 'B-95 Budimex S.A. Warszawa, ul. Ananasowa',
                'abbr' => 'B-95',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '96',
                'title' => 'B-96 BBud UG Bonn Wohnanlage Gutenbergstraße 1-3',
                'abbr' => 'B-96',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => '97',
                'title' => 'B-97 BBud UG Hennef (Sieg)',
                'abbr' => 'B-97',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => '98',
                'title' => 'B-98 Budimex Warszawa Marina Mokotów II',
                'abbr' => 'B-98',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 2,
                'code' => 'G',
                'title' => 'Germany, Sonderbetonteilwerk',
                'abbr' => 'G',
                'created_at' => now(),
            ],
            [
                'object_group_id' => 1,
                'code' => 'Ż',
                'title' => 'Żyrardów',
                'abbr' => 'Ż',
                'created_at' => now(),
            ],
        ];
        
        DB::table('objects')->insert($data);
    }
}
