<?php

use Illuminate\Database\Seeder;

class RegionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Барановичский',
                'national_name' => 'Баранавіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Берёзовский',
                'national_name' => 'Бярозаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Брестский',
                'national_name' => 'Брэсцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Ганцевичский',
                'national_name' => 'Ганцавіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Дрогичинский',
                'national_name' => 'Драгічынскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Жабинковский',
                'national_name' => 'Жабінкаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Ивановский',
                'national_name' => 'Іванаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Ивацевичский',
                'national_name' => 'Івацэвіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Каменецкий',
                'national_name' => 'Камянецкi',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Кобринский',
                'national_name' => 'Кобрынскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Лунинецкий',
                'national_name' => 'Лунінецкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Ляховичский',
                'national_name' => 'Ляхавіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Малоритский',
                'national_name' => 'Маларыцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Пинский',
                'national_name' => 'Пінскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Пружанский',
                'national_name' => 'Пружанскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 1,
                'title' => 'Столинский',
                'national_name' => 'Столінскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Бешенковичский',
                'national_name' => 'Бешанковіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Браславский',
                'national_name' => 'Браслаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Верхнедвинский',
                'national_name' => 'Верхнядзвінскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Витебский',
                'national_name' => 'Віцебскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Глубокский',
                'national_name' => 'Глыбоцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Городокский',
                'national_name' => 'Гарадоцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Докшицкий',
                'national_name' => 'Докшыцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Дубровенский',
                'national_name' => 'Дубровенскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Лепельский',
                'national_name' => 'Лепельскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Лиозненский',
                'national_name' => 'Лёзненскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Миорский',
                'national_name' => 'Міёрскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Оршанский',
                'national_name' => 'Аршанскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Полоцкий',
                'national_name' => 'Полацкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Поставский',
                'national_name' => 'Пастаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Россонский',
                'national_name' => 'Расонскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Сенненский',
                'national_name' => 'Сенненскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Толочинский',
                'national_name' => 'Талачынскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Ушачский',
                'national_name' => 'Ушацкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Чашникский',
                'national_name' => 'Чашніцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Шарковщинский',
                'national_name' => 'Шаркаўшчынскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 2,
                'title' => 'Шумилинский',
                'national_name' => 'Шумілінскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Брагинский',
                'national_name' => 'Брагінскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Буда-Кошелёвский',
                'national_name' => 'Буда-Кашалёўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Ветковский',
                'national_name' => 'Веткаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Гомельский',
                'national_name' => 'Гомельскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Добрушский',
                'national_name' => 'Добрушскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Ельский',
                'national_name' => 'Ельскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Житковичский',
                'national_name' => 'Жыткавіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Жлобинский',
                'national_name' => 'Жлобінскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Калинковичский',
                'national_name' => 'Калінкавіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Кормянский',
                'national_name' => 'Кармянскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Лельчицкий',
                'national_name' => 'Лельчыцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Лоевский',
                'national_name' => 'Лоеўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Мозырский',
                'national_name' => 'Мазырскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Наровлянский',
                'national_name' => 'Нараўлянскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Октябрьский',
                'national_name' => 'Акцябрскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Петриковский',
                'national_name' => 'Петрыкаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Речицкий',
                'national_name' => 'Рэчыцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Рогачёвский',
                'national_name' => 'Рагачоўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Светлогорский',
                'national_name' => 'Светлагорскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Хойникский',
                'national_name' => 'Хойніцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 3,
                'title' => 'Чечерский',
                'national_name' => 'Чачэрскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Берестовицкий',
                'national_name' => 'Бераставіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Волковысский',
                'national_name' => 'Ваўкавыскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Вороновский',
                'national_name' => 'Воранаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Гродненский',
                'national_name' => 'Гродзенскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Дятловский',
                'national_name' => 'Дзятлаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Зельвенский',
                'national_name' => 'Зэльвенскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Ивьевский',
                'national_name' => 'Іўеўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Кореличский',
                'national_name' => 'Карэліцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Лидский',
                'national_name' => 'Лідскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Мостовский',
                'national_name' => 'Мастоўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Новогрудский',
                'national_name' => 'Навагрудскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Ошмянский',
                'national_name' => 'Ашмянскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Островецкий',
                'national_name' => 'Астравецкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Свислочский',
                'national_name' => 'Свіслацкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Слонимский',
                'national_name' => 'Слонімскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Сморгонский',
                'national_name' => 'Смаргонскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 4,
                'title' => 'Щучинский',
                'national_name' => 'Шчучынскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Березинский',
                'national_name' => 'Бярэзінскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Борисовский',
                'national_name' => 'Барысаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Вилейский',
                'national_name' => 'Вілейскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Воложинский',
                'national_name' => 'Валожынскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Дзержинский',
                'national_name' => 'Дзяржынскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Клецкий',
                'national_name' => 'Клецкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Копыльский',
                'national_name' => 'Капыльскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Крупский',
                'national_name' => 'Крупскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Логойский',
                'national_name' => 'Лагойскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Любанский',
                'national_name' => 'Любанскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Минский',
                'national_name' => 'Мінскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Молодечненский',
                'national_name' => 'Маладзечанскі (Маладэчанскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Мядельский',
                'national_name' => 'Мядзельскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Несвижский',
                'national_name' => 'Нясвіжскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Пуховичский',
                'national_name' => 'Пухавіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Слуцкий',
                'national_name' => 'Слуцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Смолевичский',
                'national_name' => 'Смалявіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Солигорский',
                'national_name' => 'Салігорскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Стародорожский',
                'national_name' => 'Старадарожскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Столбцовский',
                'national_name' => 'Стаўбцоўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Узденский',
                'national_name' => 'Уздзенскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 5,
                'title' => 'Червенский',
                'national_name' => 'Чэрвеньскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Белыничский',
                'national_name' => 'Бялыніцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Бобруйский',
                'national_name' => 'Бабруйскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Быховский',
                'national_name' => 'Быхаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Глусский',
                'national_name' => 'Глускі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Горецкий',
                'national_name' => 'Горацкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Дрибинский',
                'national_name' => 'Дрыбінскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Кировский',
                'national_name' => 'Кіраўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Климовичский',
                'national_name' => 'Клімавіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Кличевский',
                'national_name' => 'Клічаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Костюковичский',
                'national_name' => 'Касцюковіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Краснопольский',
                'national_name' => 'Краснапольскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Кричевский',
                'national_name' => 'Крычаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Круглянский',
                'national_name' => 'Круглянскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Могилёвский',
                'national_name' => 'Магілёўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Мстиславский',
                'national_name' => 'Мсціслаўскі (Мсьціслаўскі)',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Осиповичский',
                'national_name' => 'Асіповіцкі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Славгородский',
                'national_name' => 'Слаўгарадскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Хотимский',
                'national_name' => 'Хоцімскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Чаусский',
                'national_name' => 'Чавускі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Чериковский',
                'national_name' => 'Чэрыкаўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 4,
                'district_id' => 6,
                'title' => 'Шкловский',
                'national_name' => 'Шклоўскі',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Бялобжегский',
                'national_name' => 'Białobrzeski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Варшавский',
                'national_name' => 'Warszawski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Варшавско-заходний',
                'national_name' => 'Warszawski zachodni',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Венгрувский',
                'national_name' => 'Węgrowski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Воломинский',
                'national_name' => 'Wołomiński',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Вышкувский',
                'national_name' => 'Wyszkowski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Гарволинский',
                'national_name' => 'Garwoliński',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Гостынинский',
                'national_name' => 'Gostyniński',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Гродзиский',
                'national_name' => 'Grodziski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Груецкий',
                'national_name' => 'Grójecki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Жирардувский',
                'national_name' => 'Żyrardowski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Журоминский',
                'national_name' => 'Żuromiński',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Зволенский',
                'national_name' => 'Zwoleński',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Козеницкий',
                'national_name' => 'Kozienicki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Легьоновский',
                'national_name' => 'Legionowski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Липский',
                'national_name' => 'Lipski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Лосицкий',
                'national_name' => 'Łosicki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Макувский',
                'national_name' => 'Makowski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Миньский',
                'national_name' => 'Miński',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Млавский',
                'national_name' => 'Mławski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Новодвурский',
                'national_name' => 'Nowodworski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Остроленский',
                'national_name' => 'Ostrołęcki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Острувский',
                'national_name' => 'Ostrowski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Отвоцкий',
                'national_name' => 'Otwocki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Плоньский',
                'national_name' => 'Płoński',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Плоцкий',
                'national_name' => 'Płocki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Прушковский',
                'national_name' => 'Pruszkowski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Пултуский',
                'national_name' => 'Pułtuski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Пшаснышский',
                'national_name' => 'Przasnyski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Пшисуский',
                'national_name' => 'Przysuski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Пясечинский',
                'national_name' => 'Piaseczyński',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Радомский',
                'national_name' => 'Radomski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Седлецкий',
                'national_name' => 'Siedlecki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Серпецкий',
                'national_name' => 'Sierpecki',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Соколувский',
                'national_name' => 'Sokołowski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Сохачевский',
                'national_name' => 'Sochaczewski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Цеханувский',
                'national_name' => 'Ciechanowski',
                'created_at' => now(),
            ],
            [
                'country_id' => 26,
                'district_id' => 23,
                'title' => 'Шидловецкий',
                'national_name' => 'Szydłowiecki',
                'created_at' => now(),
            ],
        ];
        
        DB::table('regions')->insert($data);
    }
}
