php artisan make:controller HumanResources/BaseHumanResourcesController
php artisan make:controller HumanResources/PersonalCardsController --resource
php artisan make:controller HumanResources/AllocationController --resource
php artisan make:controller HumanResources/DocumentsController --resource
php artisan make:controller HumanResources/ProvisionsController --resource
php artisan make:controller HumanResources/RecruitmentOrdersController --resource
php artisan make:controller HumanResources/EmployeeFamiliesController --resource
php artisan make:controller HumanResources/ManningOrdersController --resource
php artisan make:controller HumanResources/PersonalPasportsController --resource
php artisan make:controller HumanResources/PersonalAddressesController --resource
php artisan make:controller HumanResources/PersonalCommunicationsController --resource
php artisan make:controller HumanResources/PersonalCitizenshipController --resource
php artisan make:controller HumanResources/PersonalEducationsController --resource
php artisan make:controller HumanResources/PersonalTaxesController --resource
php artisan make:controller HumanResources/WorkExperiencesController --resource
php artisan make:controller HumanResources/LastJobsController --resource
php artisan make:controller HumanResources/InsuranceCertificatesController --resource
php artisan make:controller HumanResources/SalaryCardsController --resource
php artisan make:controller HumanResources/MilitaryAccountingController --resource
php artisan make:controller Accounting/BaseAccountingController
php artisan make:controller Accounting/BaseTimesheetsController --resource
php artisan make:controller Accounting/AccrualTimesheetsController --resource
php artisan make:controller Accounting/DepartmentAccrualsController --resource
php artisan make:controller Accounting/WorkOrdersController --resource
php artisan make:controller Accounting/WorkOrdersAmountsController --resource
php artisan make:controller Accounting/HoursBalancesController --resource
php artisan make:controller Accounting/EmployeeAccrualsController --resource
php artisan make:controller Accounting/EmployeeAccrualCalculationsController --resource
php artisan make:controller Accounting/EmployeeAccrualMonthsController --resource
php artisan make:controller Accounting/EmployeeAccrualYearsController --resource
php artisan make:controller Accounting/EmployeeAccrualChangesController --resource
php artisan make:controller Accounting/LogAccrualErrorsController --resource
php artisan make:controller Accounting/VacationsController --resource
php artisan make:controller Accounting/VacationAmountsController --resource
php artisan make:controller Accounting/AbsenceFromWorksController --resource
php artisan make:controller Accounting/SpecialEatingsController --resource
php artisan make:controller Accounting/PayrollPreparationController --resource
php artisan make:controller Accounting/ClosingFinancialPeriodController --resource
php artisan make:controller Calculations/BaseCalculationsController
php artisan make:controller Calculations/PayrollController --resource
php artisan make:controller Calculations/PaycheckController --resource
php artisan make:controller References/BaseReferencesController
php artisan make:controller References/DepartmentsController --resource
php artisan make:controller References/DepartmentGroupsController --resource
php artisan make:controller References/TeamsController --resource
php artisan make:controller References/ObjectsController --resource
php artisan make:controller References/CurrenciesController --resource
php artisan make:controller References/CurrencyKursesController --resource
php artisan make:controller References/DocumentTypesController --resource
php artisan make:controller References/PhraseListsController --resource
php artisan make:controller References/PositionCategoriesController --resource
php artisan make:controller References/PositionProfessionsController --resource
php artisan make:controller References/PositionsController --resource
php artisan make:controller References/HolidaysController --resource
php artisan make:controller References/HoursBalanceClassifiersController --resource
php artisan make:controller References/AbsenceFromWorksController --resource
php artisan make:controller References/GroupingTypesOfAbsencesController --resource
php artisan make:controller References/TaxRatesController --resource
php artisan make:controller References/TaxRateAmountsController --resource
php artisan make:controller References/AccrualsController --resource
php artisan make:controller References/AccrualGroupsController --resource
php artisan make:controller References/AccrualRelationsController --resource
php artisan make:controller References/CalculationGroupsController --resource
php artisan make:controller References/PieceworksController --resource
php artisan make:controller References/PieceworkUnitsController --resource
php artisan make:controller References/AccountsController --resource
php artisan make:controller References/MonthsController --resource
php artisan make:controller References/YearsController --resource
php artisan make:controller References/AlgorythmsController --resource
php artisan make:controller References/RanksController --resource
php artisan make:controller References/PhraseListGroupsController --resource
php artisan make:controller References/DismissalReasonsController --resource
php artisan make:controller References/FamilyRelationTypesController --resource
php artisan make:controller References/CommunicationTypesController --resource
php artisan make:controller References/EmploymentTypesController --resource
php artisan make:controller References/EducationTypesController --resource
php artisan make:controller References/StudyModesController --resource
php artisan make:controller References/TaxOfficesController --resource
php artisan make:controller References/TaxRecipientsController --resource
php artisan make:controller References/ObjectGroupsController --resource
php artisan make:controller References/SubordinationsController --resource
php artisan make:controller References/WorkWeekTypesController --resource
php artisan make:controller References/NationalitiesController --resource
php artisan make:controller References/CitiesController --resource
php artisan make:controller References/RegionsController --resource
php artisan make:controller References/DistrictsController --resource
php artisan make:controller References/CountriesController --resource
php artisan make:controller References/MaritalStatusesController --resource
php artisan make:controller References/ClothingSizesController --resource
php artisan make:controller References/ShoeSizesController --resource
php artisan make:controller References/DisabilitiesController --resource
php artisan make:controller References/ManningTablesController --resource
php artisan make:controller References/TaxScalesController --resource
php artisan make:controller Settings/BaseSettingsController
php artisan make:controller Settings/CalculationSetupsController --resource
php artisan make:controller Settings/CompanyDatasController --resource
php artisan make:controller Settings/ConstantsController --resource
php artisan make:controller Settings/RestoreDatabasesController --resource
php artisan make:controller Settings/SaveDatabasesController --resource